### PR TITLE
Add Setup Action

### PR DESCRIPTION
**Pull request by kevinkupski**
Relates to https://github.com/setopsco/product/issues/93

See the README.md file for the features of this PR.

### CODE REVIEW

**Review by Shark — COMMENTED** [review]
Add MPL, add reference to Terraform
https://github.com/hashicorp/setup-terraform/blob/master/LICENSE

**Comment by Shark** [comment]
Only if you have a quickfix in mind, the action prints a deprecation:

```
(node:1579) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

**Review by Shark — APPROVED** [review]
Looks good, works good 👍

**Comment by kevinkupski** [comment]
> Only if you have a quickfix in mind, the action prints a deprecation:
> 
> ```
> (node:1579) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
> ```

Unfortunately it's a package which is pulled in as a dependency. It specifically offers it as an unsafe option and only uses it, when the safe function is not available.
decompress-tar -> tar-stream -> buffer-alloc -> buffer-alloc-unsafe

**Pull request merged**
